--1) Attribute Change Tracking
 
  CREATE TABLE "CARS_INT"."ATTRIBUTE_CHANGE_TRACKING" 
   (	"ACT_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"ACT_ATTR_ID" NUMBER(12,0) NOT NULL ENABLE, 
	"ACT_TYPE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"ACT_ACTION" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"ACT_OLD_VALUE" VARCHAR2(2000), 
	"ACT_NEW_VALUE" VARCHAR2(2000), 
	"ACT_RESYNCH_CARS" CHAR(1 BYTE) DEFAULT 'N', 
	"ACT_SEND_CMP_BM" CHAR(1 BYTE) DEFAULT 'N', 
	"ACT_PROCESSED" CHAR(1 BYTE) DEFAULT 'Y', 
	"ACT_CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"ACT_UPDATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "XPKATTRIBUTE_CHANGE_TRACKING" PRIMARY KEY ("ACT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CARS_REFIX"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CARS_REF" ;
 

 
CREATE SEQUENCE  "CARS_INT"."ATTRIBUTE_TRACKING_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;


--2) Temp Table


  CREATE TABLE "CARS_INT"."TMP_ATTRIBUTE_RESYNC" 
   (	"ID" NUMBER, 
	"CAR_ID" NUMBER, 
	"ATTR_ID" NUMBER, 
	"ATTR_NAME" VARCHAR2(100 BYTE), 
	"CAR_ATTR_ID" NUMBER, 
	"ATTR_OLD_VALUE" VARCHAR2(2000), 
	"ATTR_VALUE" VARCHAR2(2000), 
	"ACTION" VARCHAR2(1 BYTE), 
	"ACT_TYPE" VARCHAR2(50 BYTE), 
	"ACT_ACTION" VARCHAR2(50 BYTE), 
	"SYS_TIMESTAMP" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CARS_INT_REQUEST" ;
 
 CREATE SEQUENCE tmp_attribute_resync_seq MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE ORDER NOCYCLE ;


--3) Audit Table

  CREATE TABLE "CARS_INT"."ATTRIBUTE_RESYNC_BATCH_AUDIT" 
   (	"BATCH_ID" NUMBER, 
	"ID" NUMBER, 
	"CAR_ID" NUMBER, 
	"ATTR_ID" NUMBER, 
	"ATTR_NAME" VARCHAR2(100 BYTE), 
	"CAR_ATTR_ID" NUMBER, 
	"ATTR_OLD_VALUE" VARCHAR2(2000), 
	"ATTR_VALUE" VARCHAR2(2000), 
	"ACTION" VARCHAR2(1 BYTE), 
	"ACT_TYPE" VARCHAR2(50 BYTE), 
	"ACT_ACTION" VARCHAR2(50 BYTE), 
	"SYS_TIMESTAMP" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CARS_INT_REQUEST" ;
 

CREATE SEQUENCE attribute_resync_audit_seq MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE ORDER NOCYCLE ;

--4) view v_attribute_tracking


  CREATE OR REPLACE FORCE VIEW "CARS_INT"."V_ATTRIBUTE_TRACKING" ("ACT_ID", "ACT_ATTR_ID", "ACT_TYPE", "ACT_ACTION", "ACT_OLD_VALUE", "ACT_NEW_VALUE", "ACT_RESYNCH_CARS", "ACT_SEND_CMP_BM", "ACT_PROCESSED", "ACT_CREATED_DATE", "ACT_UPDATED_DATE") AS 
  select a."ACT_ID",a."ACT_ATTR_ID",a."ACT_TYPE",a."ACT_ACTION",a."ACT_OLD_VALUE",a."ACT_NEW_VALUE",a."ACT_RESYNCH_CARS",a."ACT_SEND_CMP_BM",a."ACT_PROCESSED",a."ACT_CREATED_DATE",a."ACT_UPDATED_DATE" from attribute_change_tracking a,
          (
          select max(act_id) max_act_id
          from attribute_change_tracking
          --where lower(act_type) = 'attributes'
          group by act_attr_id, act_type, act_new_value
          ) b
          where act_processed = 'N'
          --and lower(act_action) = 'delete' 
          and a.act_id = b.max_act_id
          order by act_type, act_action, act_attr_id, act_id;
 

--5) Insert into config

insert into config values('ATTR_RESYNCH_BMI_EXPORT_DIRECTORY','/cars/data/carsdata/attribute_resync/','CARS','CARS',sysdate,sysdate);

insert into config values('BMI_EXPORT_FTP_ATTRIBUTE_REMOTE_DIRECTORY','/www/a/bm903-cmp/interface_load/cars_attribute_update/data','CARS','CARS',sysdate,sysdate);

insert into CONFIG values('SCHEDULED_PROCESS_ERROR_NOTIFICATION_LIST_BMIWRITE','vijay@skillnetinc.com','CARS','CARS','11-02-14','11-02-14');
insert into CONFIG values('BMI_EXPORT_FTP_HOST','10.1.48.107','CARS','CARS','11-02-14','11-02-14');
insert into CONFIG values('BMI_EXPORT_FTP_USERNAME','bmadmin','CARS','CARS','11-02-14','11-02-14');
insert into CONFIG values('BMI_EXPORT_FTP_PASSWORD','red8tonic','CARS','CARS','11-02-14','11-02-14');

commit;

--6) for the custom package..

CREATE OR REPLACE TYPE varchar2_ntt AS TABLE OF VARCHAR2(4000);


