package com.belk.car.app.model;

// Generated Jan 14, 2008 10:48:27 PM by Hibernate Tools 3.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CarSampleId generated by hbm2java
 */
@Embeddable
public class CarSampleId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4476981830813380781L;
	private long carId;
	private long sampleId;

	public CarSampleId() {
	}

	public CarSampleId(long carId, long sampleId) {
		this.carId = carId;
		this.sampleId = sampleId;
	}

	@Column(name = "CAR_ID", nullable = false, precision = 12, scale = 0)
	public long getCarId() {
		return this.carId;
	}

	public void setCarId(long carId) {
		this.carId = carId;
	}

	@Column(name = "SAMPLE_ID", nullable = false, precision = 12, scale = 0)
	public long getSampleId() {
		return this.sampleId;
	}

	public void setSampleId(long sampleId) {
		this.sampleId = sampleId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CarSampleId))
			return false;
		CarSampleId castOther = (CarSampleId) other;

		return (this.getCarId() == castOther.getCarId())
				&& (this.getSampleId() == castOther.getSampleId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCarId();
		result = 37 * result + (int) this.getSampleId();
		return result;
	}

}
