package com.belk.car.app.model;

// Generated Jan 14, 2008 10:48:27 PM by Hibernate Tools 3.2.0.CR1

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/** 
 * The CarSample generated by hbm2java
 */
@Entity
@Table(name = "CAR_SAMPLE")
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class CarSample extends BaseAuditableModel implements java.io.Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -3704463497979330698L;

	private CarSampleId id;
	private Car car;
	private Sample sample;

	public CarSample() {
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "carId", column = @Column(name = "CAR_ID", nullable = false, precision = 12, scale = 0)),
			@AttributeOverride(name = "sampleId", column = @Column(name = "SAMPLE_ID", nullable = false, precision = 12, scale = 0)) })
	public CarSampleId getId() {
		return this.id;
	}

	public void setId(CarSampleId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CAR_ID", nullable = false, insertable = false, updatable = false)
	public Car getCar() {
		return this.car;
	}

	public void setCar(Car car) {
		this.car = car;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SAMPLE_ID", nullable = false, insertable = false, updatable = false)
	public Sample getSample() {
		return this.sample;
	}

	public void setSample(Sample sample) {
		this.sample = sample;
	}

	@Column(name = "CREATED_BY", nullable = false, length = 100)
	public String getCreatedBy() {
		return this.createdBy;
	}

	@Column(name = "UPDATED_BY", nullable = false, length = 100)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", nullable = false)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATED_DATE", nullable = false)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

}
