package com.belk.car.app.model;

// Generated Jan 14, 2008 10:48:27 PM by Hibernate Tools 3.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CollectionSkusId generated by hbm2java
 */
@Embeddable
public class CollectionSkusId implements java.io.Serializable {

	private static final long serialVersionUID = -4867725046932111115L;
	/**
	 * 
	 */
	
	private String skuCode;
	private String prodCode;

	public CollectionSkusId() {
	}

	public CollectionSkusId(String skuCode, String prodCode) {
		this.skuCode = skuCode;
		this.prodCode = prodCode;
	}

	@Column(name = "SKU_CODE", nullable = false, precision = 12, scale = 0)
	public String getSkuCode() {
		return this.skuCode;
	}

	public void setSkuCode(String skuCode) {
		this.skuCode = skuCode;
	}

	@Column(name = "PROD_CODE", nullable = false, precision = 12, scale = 0)
	public String getProdCode() {
		return this.prodCode;
	}

	public void setProdCode(String prodCode) {
		this.prodCode = prodCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CollectionSkusId))
			return false;
		CollectionSkusId castOther = (CollectionSkusId) other;

		return (this.getSkuCode() == castOther.getSkuCode())
				&& (this.getProdCode() == castOther.getProdCode());
	}

	/*public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getSkuCode();
		result = 37 * result + (int) this.getProdCode();
		return result;
	}*/

}
